### ISSUE TITLE
Use new PLMD Doc Standards for JavaDoc Notation

### ISSUE THREAD

**Issue by martindsouza** [Doag/PL-SQL-Conventions#1]
We now have a good reason as to why using JavaDoc (i.e. auto generating documentation).

We have a best practice and complete documentation here: https://github.com/OraOpenSource/plsql-md-doc/blob/master/docs/javadoc.md

Template: https://github.com/OraOpenSource/plsql-md-doc/blob/master/docs/javadoc-template.md

We will be keeping that site maintained. Instead of https://github.com/Doag/PL-SQL-Conventions/blob/master/articles/codedocs.md please references the above pages.

**Comment by nielsdebr** [comment]
I have changed the contents and referenced your page. Is this what you wanted?

**Comment by martindsouza** [comment]
@nielsdebr Did you push your changes? ;-)

**Comment by nielsdebr** [comment]
I edited the changes directly on github.com, so they should be visible. I deleted the code snippet, as this is already on your site.
