### ISSUE TITLE
deployment.md

### ISSUE THREAD

**Issue by RichardSoule** [Doag/PL-SQL-Conventions#3]
Link is broken...

Bryn's EBR Training Day is probably the way to go, and potentially, use a google search instead of a direct link, although I just tried one and it appears that maybe Oracle took down Bryn's content on their site?

Anyway, this should be there:

https://www.youtube.com/playlist?list=PL22OaGrT53hVXrAYvG2CYnZ0eKvDxIcg8

**Comment by nielsdebr** [comment]
Thanks for mentioning this. I have changed the URL.

Would you like to be a member of this repository? We always look for people that want to contribute.

**Comment by RichardSoule** [comment]
Sure. I'd love to provide some feedback and/or updates.
